version: '3.8'

services:
  fenics:
    image: quay.io/fenicsproject/stable:current
    container_name: fenics_container
    volumes:
      - ./:/home/fenics/shared
    working_dir: /home/fenics/shared
    ports:
      - "8888:8888"
    command: >
      bash -c "jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root"
